### ISSUE TITLE
How to build on arm Linux ?

### ISSUE THREAD

**Issue by HolmesShuan** [tianylijun/FeatherCNNEx#1]
Hi, FeatherCNNEx with FP16 and INT8 is definitely a good job! Could you please share more information about `how to build on arm Ubuntu`? I have tried the same procedure as FeatherCNN but failed. Hopefully, you may give me a hint. Thanks.

**Comment by tianylijun** [comment]
sorry for late response, you can build the project just run the build cmd, such as build_android_arm32.sh with clang, or build_android_arm32-gcc.sh  with gcc.
