### ISSUE TITLE
ncnn 和 FeatherCNNEx 测试对比

### ISSUE THREAD

**Issue by fangbaolei** [tianylijun/FeatherCNNEx#2]
![image](https://user-images.githubusercontent.com/7870889/46708505-7fa9b800-cc71-11e8-9a0c-6d802cdc72f5.png)
我看了这个你们对比了RokidCNN和NCNN的数据，RokidCNN提升很多，想知道这里的RokidCNN就是开源的FeatherCNNEx测试的结果，还是其他引擎测试的，如果是是FeatherCNNEx有没有参照测试方法，谢谢

**Comment by tianylijun** [comment]
pls ref the latest readme
